//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minax.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minax.Languages.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account Permission Error 的當地語系化字串。
        /// </summary>
        internal static string Str0AccountPermissionError {
            get {
                return ResourceManager.GetString("Str0AccountPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Detect 的當地語系化字串。
        /// </summary>
        internal static string Str0AutoDetect {
            get {
                return ResourceManager.GetString("Str0AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string Str0Clear {
            get {
                return ResourceManager.GetString("Str0Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect Error 的當地語系化字串。
        /// </summary>
        internal static string Str0ConnectError {
            get {
                return ResourceManager.GetString("Str0ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connecting... 的當地語系化字串。
        /// </summary>
        internal static string Str0Connecting {
            get {
                return ResourceManager.GetString("Str0Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CSV file(*.csv)|.csv 的當地語系化字串。
        /// </summary>
        internal static string Str0FileFilterCsv {
            get {
                return ResourceManager.GetString("Str0FileFilterCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simplified Chinese 的當地語系化字串。
        /// </summary>
        internal static string Str0LangChs {
            get {
                return ResourceManager.GetString("Str0LangChs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tranditional Chinese 的當地語系化字串。
        /// </summary>
        internal static string Str0LangCht {
            get {
                return ResourceManager.GetString("Str0LangCht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English 的當地語系化字串。
        /// </summary>
        internal static string Str0LangEn {
            get {
                return ResourceManager.GetString("Str0LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japan 的當地語系化字串。
        /// </summary>
        internal static string Str0LangJapan {
            get {
                return ResourceManager.GetString("Str0LangJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language changed... Please restart this program to take effect! 的當地語系化字串。
        /// </summary>
        internal static string Str0LanguageChanged {
            get {
                return ResourceManager.GetString("Str0LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message 的當地語系化字串。
        /// </summary>
        internal static string Str0Message {
            get {
                return ResourceManager.GetString("Str0Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Network Connector Missing! 的當地語系化字串。
        /// </summary>
        internal static string Str0NetworkConnectorError {
            get {
                return ResourceManager.GetString("Str0NetworkConnectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check your network settings or ask your administrator for help! 的當地語系化字串。
        /// </summary>
        internal static string Str0NetworkError {
            get {
                return ResourceManager.GetString("Str0NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Data 的當地語系化字串。
        /// </summary>
        internal static string Str0NoData {
            get {
                return ResourceManager.GetString("Str0NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string Str0OK {
            get {
                return ResourceManager.GetString("Str0OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation failed! 的當地語系化字串。
        /// </summary>
        internal static string Str0OperationFailed {
            get {
                return ResourceManager.GetString("Str0OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation successful. 的當地語系化字串。
        /// </summary>
        internal static string Str0OperationSuccessful {
            get {
                return ResourceManager.GetString("Str0OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OriginalText cannot be empty! 的當地語系化字串。
        /// </summary>
        internal static string Str0OriginalTextCantEmpty {
            get {
                return ResourceManager.GetString("Str0OriginalTextCantEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password mismatched! 的當地語系化字串。
        /// </summary>
        internal static string Str0PasswordMismatched {
            get {
                return ResourceManager.GetString("Str0PasswordMismatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission Deny! 的當地語系化字串。
        /// </summary>
        internal static string Str0PermissionDeny {
            get {
                return ResourceManager.GetString("Str0PermissionDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait for cloud operation finished. 的當地語系化字串。
        /// </summary>
        internal static string Str0PleaseWaitCloudOperation {
            get {
                return ResourceManager.GetString("Str0PleaseWaitCloudOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait for operation finished. 的當地語系化字串。
        /// </summary>
        internal static string Str0PleaseWaitOperation {
            get {
                return ResourceManager.GetString("Str0PleaseWaitOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Processing... 的當地語系化字串。
        /// </summary>
        internal static string Str0Processing {
            get {
                return ResourceManager.GetString("Str0Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Runtime Error 的當地語系化字串。
        /// </summary>
        internal static string Str0RuntimeError {
            get {
                return ResourceManager.GetString("Str0RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string Str0Save {
            get {
                return ResourceManager.GetString("Str0Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown 的當地語系化字串。
        /// </summary>
        internal static string Str0Unknown {
            get {
                return ResourceManager.GetString("Str0Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        internal static string Str0Warning {
            get {
                return ResourceManager.GetString("Str0Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The {0} argument is invalid! 的當地語系化字串。
        /// </summary>
        internal static string Str1ArgumentIsInvalid {
            get {
                return ResourceManager.GetString("Str1ArgumentIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connect to {0} failed! 的當地語系化字串。
        /// </summary>
        internal static string Str1ConnecToFailed {
            get {
                return ResourceManager.GetString("Str1ConnecToFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0:yyMMdd_HHmmss} 的當地語系化字串。
        /// </summary>
        internal static string Str1DateTimeFileNameFormat {
            get {
                return ResourceManager.GetString("Str1DateTimeFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Something wrong! Message: {0} 的當地語系化字串。
        /// </summary>
        internal static string Str1SomethingWrongMSG {
            get {
                return ResourceManager.GetString("Str1SomethingWrongMSG", resourceCulture);
            }
        }
    }
}
