//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minax.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextCategory() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minax.Languages.TextCategory", typeof(TextCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Accessory 的當地語系化字串。
        /// </summary>
        public static string Str0Accessory {
            get {
                return ResourceManager.GetString("Str0Accessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action 的當地語系化字串。
        /// </summary>
        public static string Str0Action {
            get {
                return ResourceManager.GetString("Str0Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adjective 的當地語系化字串。
        /// </summary>
        public static string Str0Adjective {
            get {
                return ResourceManager.GetString("Str0Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Adverb 的當地語系化字串。
        /// </summary>
        public static string Str0Adverb {
            get {
                return ResourceManager.GetString("Str0Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alchemy 的當地語系化字串。
        /// </summary>
        public static string Str0Alchemy {
            get {
                return ResourceManager.GetString("Str0Alchemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alias Name 的當地語系化字串。
        /// </summary>
        public static string Str0AliasName {
            get {
                return ResourceManager.GetString("Str0AliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Animal 的當地語系化字串。
        /// </summary>
        public static string Str0Animal {
            get {
                return ResourceManager.GetString("Str0Animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Body Organ 的當地語系化字串。
        /// </summary>
        public static string Str0BodyOrgan {
            get {
                return ResourceManager.GetString("Str0BodyOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Book 的當地語系化字串。
        /// </summary>
        public static string Str0Book {
            get {
                return ResourceManager.GetString("Str0Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Building 的當地語系化字串。
        /// </summary>
        public static string Str0Building {
            get {
                return ResourceManager.GetString("Str0Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Car 的當地語系化字串。
        /// </summary>
        public static string Str0Car {
            get {
                return ResourceManager.GetString("Str0Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Character 的當地語系化字串。
        /// </summary>
        public static string Str0Character {
            get {
                return ResourceManager.GetString("Str0Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 City 的當地語系化字串。
        /// </summary>
        public static string Str0City {
            get {
                return ResourceManager.GetString("Str0City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clothing 的當地語系化字串。
        /// </summary>
        public static string Str0Clothing {
            get {
                return ResourceManager.GetString("Str0Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Color 的當地語系化字串。
        /// </summary>
        public static string Str0Color {
            get {
                return ResourceManager.GetString("Str0Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Conjunction 的當地語系化字串。
        /// </summary>
        public static string Str0Conjunction {
            get {
                return ResourceManager.GetString("Str0Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Determiners 的當地語系化字串。
        /// </summary>
        public static string Str0Determiners {
            get {
                return ResourceManager.GetString("Str0Determiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dialect 的當地語系化字串。
        /// </summary>
        public static string Str0Dialect {
            get {
                return ResourceManager.GetString("Str0Dialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Education 的當地語系化字串。
        /// </summary>
        public static string Str0Education {
            get {
                return ResourceManager.GetString("Str0Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Entertainment 的當地語系化字串。
        /// </summary>
        public static string Str0Entertainment {
            get {
                return ResourceManager.GetString("Str0Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Facility 的當地語系化字串。
        /// </summary>
        public static string Str0Facility {
            get {
                return ResourceManager.GetString("Str0Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Family Name 的當地語系化字串。
        /// </summary>
        public static string Str0FamilyName {
            get {
                return ResourceManager.GetString("Str0FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First Name 的當地語系化字串。
        /// </summary>
        public static string Str0FirstName {
            get {
                return ResourceManager.GetString("Str0FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Food 的當地語系化字串。
        /// </summary>
        public static string Str0Food {
            get {
                return ResourceManager.GetString("Str0Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Game 的當地語系化字串。
        /// </summary>
        public static string Str0Game {
            get {
                return ResourceManager.GetString("Str0Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hair Style 的當地語系化字串。
        /// </summary>
        public static string Str0HairStyle {
            get {
                return ResourceManager.GetString("Str0HairStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Housing 的當地語系化字串。
        /// </summary>
        public static string Str0Housing {
            get {
                return ResourceManager.GetString("Str0Housing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inventory 的當地語系化字串。
        /// </summary>
        public static string Str0Inventory {
            get {
                return ResourceManager.GetString("Str0Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Job Position 的當地語系化字串。
        /// </summary>
        public static string Str0JobPosition {
            get {
                return ResourceManager.GetString("Str0JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string Str0Language {
            get {
                return ResourceManager.GetString("Str0Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location 的當地語系化字串。
        /// </summary>
        public static string Str0Location {
            get {
                return ResourceManager.GetString("Str0Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Machine 的當地語系化字串。
        /// </summary>
        public static string Str0Machine {
            get {
                return ResourceManager.GetString("Str0Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Magic 的當地語系化字串。
        /// </summary>
        public static string Str0Magic {
            get {
                return ResourceManager.GetString("Str0Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maneuver 的當地語系化字串。
        /// </summary>
        public static string Str0Maneuver {
            get {
                return ResourceManager.GetString("Str0Maneuver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Material 的當地語系化字串。
        /// </summary>
        public static string Str0Material {
            get {
                return ResourceManager.GetString("Str0Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Middle Name 的當地語系化字串。
        /// </summary>
        public static string Str0MiddleName {
            get {
                return ResourceManager.GetString("Str0MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Misc Terms 的當地語系化字串。
        /// </summary>
        public static string Str0MiscTerms {
            get {
                return ResourceManager.GetString("Str0MiscTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Monster 的當地語系化字串。
        /// </summary>
        public static string Str0Monster {
            get {
                return ResourceManager.GetString("Str0Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Music 的當地語系化字串。
        /// </summary>
        public static string Str0Music {
            get {
                return ResourceManager.GetString("Str0Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nickname 的當地語系化字串。
        /// </summary>
        public static string Str0NickName {
            get {
                return ResourceManager.GetString("Str0NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Noun 的當地語系化字串。
        /// </summary>
        public static string Str0Noun {
            get {
                return ResourceManager.GetString("Str0Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Object 的當地語系化字串。
        /// </summary>
        public static string Str0Object {
            get {
                return ResourceManager.GetString("Str0Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Organization 的當地語系化字串。
        /// </summary>
        public static string Str0Organization {
            get {
                return ResourceManager.GetString("Str0Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Other Name 的當地語系化字串。
        /// </summary>
        public static string Str0OtherName {
            get {
                return ResourceManager.GetString("Str0OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phenomenon 的當地語系化字串。
        /// </summary>
        public static string Str0Phenomenon {
            get {
                return ResourceManager.GetString("Str0Phenomenon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preposition 的當地語系化字串。
        /// </summary>
        public static string Str0Preposition {
            get {
                return ResourceManager.GetString("Str0Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pronouns 的當地語系化字串。
        /// </summary>
        public static string Str0Pronouns {
            get {
                return ResourceManager.GetString("Str0Pronouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Property 的當地語系化字串。
        /// </summary>
        public static string Str0Property {
            get {
                return ResourceManager.GetString("Str0Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reincarnated Name 的當地語系化字串。
        /// </summary>
        public static string Str0ReincarnatedName {
            get {
                return ResourceManager.GetString("Str0ReincarnatedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Relation 的當地語系化字串。
        /// </summary>
        public static string Str0Relation {
            get {
                return ResourceManager.GetString("Str0Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Science 的當地語系化字串。
        /// </summary>
        public static string Str0Science {
            get {
                return ResourceManager.GetString("Str0Science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ship 的當地語系化字串。
        /// </summary>
        public static string Str0Ship {
            get {
                return ResourceManager.GetString("Str0Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shoe 的當地語系化字串。
        /// </summary>
        public static string Str0Shoe {
            get {
                return ResourceManager.GetString("Str0Shoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Social 的當地語系化字串。
        /// </summary>
        public static string Str0Social {
            get {
                return ResourceManager.GetString("Str0Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Species 的當地語系化字串。
        /// </summary>
        public static string Str0Species {
            get {
                return ResourceManager.GetString("Str0Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translator 的當地語系化字串。
        /// </summary>
        public static string Str0Translator {
            get {
                return ResourceManager.GetString("Str0Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Transportation 的當地語系化字串。
        /// </summary>
        public static string Str0Transportation {
            get {
                return ResourceManager.GetString("Str0Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Undefined 的當地語系化字串。
        /// </summary>
        public static string Str0Undefined {
            get {
                return ResourceManager.GetString("Str0Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verbs 的當地語系化字串。
        /// </summary>
        public static string Str0Verbs {
            get {
                return ResourceManager.GetString("Str0Verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weapon 的當地語系化字串。
        /// </summary>
        public static string Str0Weapon {
            get {
                return ResourceManager.GetString("Str0Weapon", resourceCulture);
            }
        }
    }
}
