//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinaxWebTranslator.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AvalonDockLayout {
            get {
                return ((string)(this["AvalonDockLayout"]));
            }
            set {
                this["AvalonDockLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomGlossaryFileListLocations {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomGlossaryFileListLocations"]));
            }
            set {
                this["CustomGlossaryFileListLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int QuickTranslationWordMax {
            get {
                return ((int)(this["QuickTranslationWordMax"]));
            }
            set {
                this["QuickTranslationWordMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/nuthrash/Minax/raw/master/MinaxWebTranslator/TranslationProjec" +
            "ts/GlossaryFileList.txt")]
        public string DefaultGlossaryFileListLocation {
            get {
                return ((string)(this["DefaultGlossaryFileListLocation"]));
            }
            set {
                this["DefaultGlossaryFileListLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Excite")]
        public string RemoteXlatorType {
            get {
                return ((string)(this["RemoteXlatorType"]));
            }
            set {
                this["RemoteXlatorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorCrypto {
            get {
                return ((string)(this["XlatorCrypto"]));
            }
            set {
                this["XlatorCrypto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorBaiduAppId {
            get {
                return ((string)(this["XlatorBaiduAppId"]));
            }
            set {
                this["XlatorBaiduAppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorBaiduSecretKey {
            get {
                return ((string)(this["XlatorBaiduSecretKey"]));
            }
            set {
                this["XlatorBaiduSecretKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorYoudaoAppKey {
            get {
                return ((string)(this["XlatorYoudaoAppKey"]));
            }
            set {
                this["XlatorYoudaoAppKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorYoudaoAppSecret {
            get {
                return ((string)(this["XlatorYoudaoAppSecret"]));
            }
            set {
                this["XlatorYoudaoAppSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorGoogleApiKey {
            get {
                return ((string)(this["XlatorGoogleApiKey"]));
            }
            set {
                this["XlatorGoogleApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorMicrosoftSubKey {
            get {
                return ((string)(this["XlatorMicrosoftSubKey"]));
            }
            set {
                this["XlatorMicrosoftSubKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorMicrosoftSubRegion {
            get {
                return ((string)(this["XlatorMicrosoftSubRegion"]));
            }
            set {
                this["XlatorMicrosoftSubRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XlatorMicrosoftServer {
            get {
                return ((string)(this["XlatorMicrosoftServer"]));
            }
            set {
                this["XlatorMicrosoftServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemeberRecentProjects {
            get {
                return ((bool)(this["RemeberRecentProjects"]));
            }
            set {
                this["RemeberRecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int RecentProjectCountMax {
            get {
                return ((int)(this["RecentProjectCountMax"]));
            }
            set {
                this["RecentProjectCountMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonitorAutoMergeWhenFileChanged {
            get {
                return ((bool)(this["MonitorAutoMergeWhenFileChanged"]));
            }
            set {
                this["MonitorAutoMergeWhenFileChanged"] = value;
            }
        }
    }
}
