//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinaxWebTranslator.Desktop.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectGlossary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectGlossary() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinaxWebTranslator.Desktop.Languages.ProjectGlossary", typeof(ProjectGlossary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Glossary File List 的當地語系化字串。
        /// </summary>
        public static string Str0AddGlossaryFileList {
            get {
                return ResourceManager.GetString("Str0AddGlossaryFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Mapping Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0AddMappingConfirm {
            get {
                return ResourceManager.GetString("Str0AddMappingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add New Mapping 的當地語系化字串。
        /// </summary>
        public static string Str0AddNewMapping {
            get {
                return ResourceManager.GetString("Str0AddNewMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add remote glossary file list text file 的當地語系化字串。
        /// </summary>
        public static string Str0AddRemoteGlossaryFileListTextFile {
            get {
                return ResourceManager.GetString("Str0AddRemoteGlossaryFileListTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All glossary files fetched. 的當地語系化字串。
        /// </summary>
        public static string Str0AllGlossaryFileFetched {
            get {
                return ResourceManager.GetString("Str0AllGlossaryFileFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Always Asking 的當地語系化字串。
        /// </summary>
        public static string Str0AlwaysAsking {
            get {
                return ResourceManager.GetString("Str0AlwaysAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 App Settings 的當地語系化字串。
        /// </summary>
        public static string Str0AppSettings {
            get {
                return ResourceManager.GetString("Str0AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto merge Glossary Mapping entries when file added, deleted, changed 的當地語系化字串。
        /// </summary>
        public static string Str0AutoMergeGlossaryMappingEntriesWhenFileChanged {
            get {
                return ResourceManager.GetString("Str0AutoMergeGlossaryMappingEntriesWhenFileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This option does not contain Project file itself, system would always ask user for prompting! 的當地語系化字串。
        /// </summary>
        public static string Str0AutoMergeGlossaryMappingEntriesWhenFileChangedToolTip {
            get {
                return ResourceManager.GetString("Str0AutoMergeGlossaryMappingEntriesWhenFileChangedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto modify Mapping content when file renamed 的當地語系化字串。
        /// </summary>
        public static string Str0AutoModifyMappingContentWhenFileRenamed {
            get {
                return ResourceManager.GetString("Str0AutoModifyMappingContentWhenFileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bigger File Size 的當地語系化字串。
        /// </summary>
        public static string Str0BiggerFileSize {
            get {
                return ResourceManager.GetString("Str0BiggerFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cannot fetch the remote glossary list file. 的當地語系化字串。
        /// </summary>
        public static string Str0CantFetchRemoteGlossaryFileList {
            get {
                return ResourceManager.GetString("Str0CantFetchRemoteGlossaryFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        public static string Str0Category {
            get {
                return ResourceManager.GetString("Str0Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure want to clear existed Recent Project List? 的當地語系化字串。
        /// </summary>
        public static string Str0ClearExistedRecentProjectListAsk {
            get {
                return ResourceManager.GetString("Str0ClearExistedRecentProjectListAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear Recent Project List 的當地語系化字串。
        /// </summary>
        public static string Str0ClearRecentProjectList {
            get {
                return ResourceManager.GetString("Str0ClearRecentProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Count: 的當地語系化字串。
        /// </summary>
        public static string Str0Count {
            get {
                return ResourceManager.GetString("Str0Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create empty glossary sub-folders 的當地語系化字串。
        /// </summary>
        public static string Str0CreateEmptyGlossarySubfolders {
            get {
                return ResourceManager.GetString("Str0CreateEmptyGlossarySubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create empty glossary sub-folders in local project folder 的當地語系化字串。
        /// </summary>
        public static string Str0CreateEmptyGlossarySubfoldersToolTip {
            get {
                return ResourceManager.GetString("Str0CreateEmptyGlossarySubfoldersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Glossary sub-folders failed!! 的當地語系化字串。
        /// </summary>
        public static string Str0CreateGlossaryFolderFailed {
            get {
                return ResourceManager.GetString("Str0CreateGlossaryFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Glossary sub-folders succeed! 的當地語系化字串。
        /// </summary>
        public static string Str0CreateGlossaryFolderSucceed {
            get {
                return ResourceManager.GetString("Str0CreateGlossaryFolderSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Glossary Path: 的當地語系化字串。
        /// </summary>
        public static string Str0CurrentGlossaryPath {
            get {
                return ResourceManager.GetString("Str0CurrentGlossaryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current project saved. 的當地語系化字串。
        /// </summary>
        public static string Str0CurrentProjectSaved {
            get {
                return ResourceManager.GetString("Str0CurrentProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete selected file list text file 的當地語系化字串。
        /// </summary>
        public static string Str0DeleteSelectedFileList {
            get {
                return ResourceManager.GetString("Str0DeleteSelectedFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description: 的當地語系化字串。
        /// </summary>
        public static string Str0Description {
            get {
                return ResourceManager.GetString("Str0Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download and merge remote Glossary file(s) succeed! 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadAndMergeRemoteGlossaryFilesSucceed {
            get {
                return ResourceManager.GetString("Str0DownloadAndMergeRemoteGlossaryFilesSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download remote Glossary file(s) succeed,  then please wait for reloading all Mapping tables. 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadGlossaryFilesSucceedWaitReloading {
            get {
                return ResourceManager.GetString("Str0DownloadGlossaryFilesSucceedWaitReloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Downloading remote Glossary file(s)... 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadingRemoteGlossaryFiles {
            get {
                return ResourceManager.GetString("Str0DownloadingRemoteGlossaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download latest glossary files 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadLatestGlossaryFiles {
            get {
                return ResourceManager.GetString("Str0DownloadLatestGlossaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download latest glossary files from remote public web site by Sync. File. 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadLatestGlossaryFilesToolTip {
            get {
                return ResourceManager.GetString("Str0DownloadLatestGlossaryFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download remote Glossary file(s) by file list link failed! 的當地語系化字串。
        /// </summary>
        public static string Str0DownloadRemoteGlossaryFilesByLinkFailed {
            get {
                return ResourceManager.GetString("Str0DownloadRemoteGlossaryFilesByLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Changed Monitor 的當地語系化字串。
        /// </summary>
        public static string Str0FileChangedMonitor {
            get {
                return ResourceManager.GetString("Str0FileChangedMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File list cannot be feteched or may be an invalid formatted text file! 的當地語系化字串。
        /// </summary>
        public static string Str0FileListCantFetchOrInvalid {
            get {
                return ResourceManager.GetString("Str0FileListCantFetchOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File list count has reach maximum!! 的當地語系化字串。
        /// </summary>
        public static string Str0FileListCountHasReachMaximum {
            get {
                return ResourceManager.GetString("Str0FileListCountHasReachMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File list location: 的當地語系化字串。
        /// </summary>
        public static string Str0FileListLocation {
            get {
                return ResourceManager.GetString("Str0FileListLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File list location is existed!! 的當地語系化字串。
        /// </summary>
        public static string Str0FileListLocationIsExisted {
            get {
                return ResourceManager.GetString("Str0FileListLocationIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Force Overwrite Without Asking 的當地語系化字串。
        /// </summary>
        public static string Str0ForceOverwriteWithoutAsking {
            get {
                return ResourceManager.GetString("Str0ForceOverwriteWithoutAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary File List Error 的當地語系化字串。
        /// </summary>
        public static string Str0GlossaryFileListError {
            get {
                return ResourceManager.GetString("Str0GlossaryFileListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary File List Warning 的當地語系化字串。
        /// </summary>
        public static string Str0GlossaryFileListWarning {
            get {
                return ResourceManager.GetString("Str0GlossaryFileListWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Group By: 的當地語系化字串。
        /// </summary>
        public static string Str0GroupBy {
            get {
                return ResourceManager.GetString("Str0GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Mapping Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0KeepMappingConfirm {
            get {
                return ResourceManager.GetString("Str0KeepMappingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Keep Recent Project List: 的當地語系化字串。
        /// </summary>
        public static string Str0KeepRecentProjectList {
            get {
                return ResourceManager.GetString("Str0KeepRecentProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Load project files failed! 的當地語系化字串。
        /// </summary>
        public static string Str0LoadProjectFilesFailed {
            get {
                return ResourceManager.GetString("Str0LoadProjectFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mapping Source Language: 的當地語系化字串。
        /// </summary>
        public static string Str0MappingSourceLanguage {
            get {
                return ResourceManager.GetString("Str0MappingSourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mapping Target Language: 的當地語系化字串。
        /// </summary>
        public static string Str0MappingTargetLanguage {
            get {
                return ResourceManager.GetString("Str0MappingTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mapping Text 的當地語系化字串。
        /// </summary>
        public static string Str0MappingText {
            get {
                return ResourceManager.GetString("Str0MappingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Merge remote Glossary file(s) failed! 的當地語系化字串。
        /// </summary>
        public static string Str0MergeGlossaryFilesFailed {
            get {
                return ResourceManager.GetString("Str0MergeGlossaryFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify Glossary File List 的當地語系化字串。
        /// </summary>
        public static string Str0ModifyGlossaryFileList {
            get {
                return ResourceManager.GetString("Str0ModifyGlossaryFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Modify selected file list location 的當地語系化字串。
        /// </summary>
        public static string Str0ModifySelectedFileList {
            get {
                return ResourceManager.GetString("Str0ModifySelectedFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move selected file list text file down 的當地語系化字串。
        /// </summary>
        public static string Str0MoveSelectedFileListDown {
            get {
                return ResourceManager.GetString("Str0MoveSelectedFileListDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Move selected file list text file up 的當地語系化字串。
        /// </summary>
        public static string Str0MoveSelectedFileListUp {
            get {
                return ResourceManager.GetString("Str0MoveSelectedFileListUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New File Date 的當地語系化字串。
        /// </summary>
        public static string Str0NewFileDate {
            get {
                return ResourceManager.GetString("Str0NewFileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New Original Text: 的當地語系化字串。
        /// </summary>
        public static string Str0NewOriginalText {
            get {
                return ResourceManager.GetString("Str0NewOriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No glossary file can fetch. 的當地語系化字串。
        /// </summary>
        public static string Str0NoGlossaryFileCanFetch {
            get {
                return ResourceManager.GetString("Str0NoGlossaryFileCanFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original Text 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalText {
            get {
                return ResourceManager.GetString("Str0OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original Text Error 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalTextError {
            get {
                return ResourceManager.GetString("Str0OriginalTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Original Text shall not be empty!! 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalTextShallNotEmpty {
            get {
                return ResourceManager.GetString("Str0OriginalTextShallNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Original Text might too short to replaced many words incorrectly!! 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalTextTooShortWarning {
            get {
                return ResourceManager.GetString("Str0OriginalTextTooShortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Original Text Warning 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalTextWarning {
            get {
                return ResourceManager.GetString("Str0OriginalTextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Original Text seems full of whitespace text, take care of it!! 的當地語系化字串。
        /// </summary>
        public static string Str0OriginalTextWhitespaceTakeCare {
            get {
                return ResourceManager.GetString("Str0OriginalTextWhitespaceTakeCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overwrite Policy: 的當地語系化字串。
        /// </summary>
        public static string Str0OverwritePolicy {
            get {
                return ResourceManager.GetString("Str0OverwritePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Same file name or folder name overwrite policy 的當地語系化字串。
        /// </summary>
        public static string Str0OverwritePolicyToolTip {
            get {
                return ResourceManager.GetString("Str0OverwritePolicyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait for reloading all Mapping Tables. 的當地語系化字串。
        /// </summary>
        public static string Str0PlzWaitReloadMappingTables {
            get {
                return ResourceManager.GetString("Str0PlzWaitReloadMappingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project Name: 的當地語系化字串。
        /// </summary>
        public static string Str0ProjectName {
            get {
                return ResourceManager.GetString("Str0ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Project Name field cannot be empty or full of whitespace text! 的當地語系化字串。
        /// </summary>
        public static string Str0ProjectNameFieldCantEmptyOrWhitespaces {
            get {
                return ResourceManager.GetString("Str0ProjectNameFieldCantEmptyOrWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project Settings 的當地語系化字串。
        /// </summary>
        public static string Str0ProjectSettings {
            get {
                return ResourceManager.GetString("Str0ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recent Project List Maximum: 的當地語系化字串。
        /// </summary>
        public static string Str0RecentProjectListMaximum {
            get {
                return ResourceManager.GetString("Str0RecentProjectListMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recent Project(s) 的當地語系化字串。
        /// </summary>
        public static string Str0RecentProjects {
            get {
                return ResourceManager.GetString("Str0RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reloading Glossary file(s) failed! 的當地語系化字串。
        /// </summary>
        public static string Str0ReloadingGlossaryFileFailed {
            get {
                return ResourceManager.GetString("Str0ReloadingGlossaryFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reloading Glossary file(s) succeed! 的當地語系化字串。
        /// </summary>
        public static string Str0ReloadingGlossaryFileSucceed {
            get {
                return ResourceManager.GetString("Str0ReloadingGlossaryFileSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remote Site: 的當地語系化字串。
        /// </summary>
        public static string Str0RemoteSite {
            get {
                return ResourceManager.GetString("Str0RemoteSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NOTE: The remote File List file stores many relative paths (to the site root) of Glossary sub-folders and files. It shall be an UTF-8 pure text file! 的當地語系化字串。
        /// </summary>
        public static string Str0RemoteSyncFileListNote {
            get {
                return ResourceManager.GetString("Str0RemoteSyncFileListNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remote Sync. File List Settings 的當地語系化字串。
        /// </summary>
        public static string Str0RemoteSyncFileListSettings {
            get {
                return ResourceManager.GetString("Str0RemoteSyncFileListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save current project failed!! 的當地語系化字串。
        /// </summary>
        public static string Str0SaveCurrentProjectFailed {
            get {
                return ResourceManager.GetString("Str0SaveCurrentProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to save modified project? 的當地語系化字串。
        /// </summary>
        public static string Str0SaveModifiedProjectAsk {
            get {
                return ResourceManager.GetString("Str0SaveModifiedProjectAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Project Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0SaveProjectConfirm {
            get {
                return ResourceManager.GetString("Str0SaveProjectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save project failed!! 的當地語系化字串。
        /// </summary>
        public static string Str0SaveProjectFailed {
            get {
                return ResourceManager.GetString("Str0SaveProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select an existed Translation Project file 的當地語系化字串。
        /// </summary>
        public static string Str0SelectExistedProjectFile {
            get {
                return ResourceManager.GetString("Str0SelectExistedProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select a preferred Translation Project file name 的當地語系化字串。
        /// </summary>
        public static string Str0SelectTranslationProjectFileName {
            get {
                return ResourceManager.GetString("Str0SelectTranslationProjectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Skip 的當地語系化字串。
        /// </summary>
        public static string Str0Skip {
            get {
                return ResourceManager.GetString("Str0Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ⚙  Sync. File: 的當地語系化字串。
        /// </summary>
        public static string Str0SyncFileSettings {
            get {
                return ResourceManager.GetString("Str0SyncFileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translation Project File(*.conf)|*.conf 的當地語系化字串。
        /// </summary>
        public static string Str0TranslationProjectExt {
            get {
                return ResourceManager.GetString("Str0TranslationProjectExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Mapping Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0UpdateMappingConfirm {
            get {
                return ResourceManager.GetString("Str0UpdateMappingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 A new Glossary file &quot;{0}&quot; has been added somewhere!
        ///Do you want to add new Mapping entries? 的當地語系化字串。
        /// </summary>
        public static string Str1AddGlossaryFileMappingAsk {
            get {
                return ResourceManager.GetString("Str1AddGlossaryFileMappingAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create project &quot;{0}&quot; failed! 的當地語系化字串。
        /// </summary>
        public static string Str1CreateProjectFailed {
            get {
                return ResourceManager.GetString("Str1CreateProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create project &quot;{0}&quot; succeed. 的當地語系化字串。
        /// </summary>
        public static string Str1CreateProjectSucceed {
            get {
                return ResourceManager.GetString("Str1CreateProjectSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary file &quot;{0}&quot; has been added and merged! 的當地語系化字串。
        /// </summary>
        public static string Str1GlossaryFileAddedAndMerged {
            get {
                return ResourceManager.GetString("Str1GlossaryFileAddedAndMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary File &quot;{0}&quot; created. 的當地語系化字串。
        /// </summary>
        public static string Str1GlossaryFileCreated {
            get {
                return ResourceManager.GetString("Str1GlossaryFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary file &quot;{0}&quot; was been deleted!
        ///Do you want to keep its Mapping entries? 的當地語系化字串。
        /// </summary>
        public static string Str1GlossaryFileDeletedKeepAsk {
            get {
                return ResourceManager.GetString("Str1GlossaryFileDeletedKeepAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary file &quot;{0}&quot; had been removed! 的當地語系化字串。
        /// </summary>
        public static string Str1GlossaryFileRemoved {
            get {
                return ResourceManager.GetString("Str1GlossaryFileRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary file &quot;{0}&quot; has been updated and merged! 的當地語系化字串。
        /// </summary>
        public static string Str1GlossaryFileUpdatedAndMerged {
            get {
                return ResourceManager.GetString("Str1GlossaryFileUpdatedAndMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Got Exception: {0} 的當地語系化字串。
        /// </summary>
        public static string Str1GotException {
            get {
                return ResourceManager.GetString("Str1GotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open project &quot;{0}&quot; failed! 的當地語系化字串。
        /// </summary>
        public static string Str1OpenProjectFailed {
            get {
                return ResourceManager.GetString("Str1OpenProjectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open project &quot;{0}&quot; succeed. 的當地語系化字串。
        /// </summary>
        public static string Str1OpenProjectSucceed {
            get {
                return ResourceManager.GetString("Str1OpenProjectSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry! The Original Text of new Mapping &quot;{0}&quot; duplicated with existed item!! 的當地語系化字串。
        /// </summary>
        public static string Str1OriginalTextDupicatedWarning {
            get {
                return ResourceManager.GetString("Str1OriginalTextDupicatedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary File &quot;{0}&quot; existed, do you want to OVERWRITE it? 的當地語系化字串。
        /// </summary>
        public static string Str1OverwriteGlossaryFileAsk {
            get {
                return ResourceManager.GetString("Str1OverwriteGlossaryFileAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project file &quot;{0}&quot; has been modified somewhere!
        ///Do you want to save current project configuration file to OVERWRITE it? 的當地語系化字串。
        /// </summary>
        public static string Str1OverwriteProjectFileAsk {
            get {
                return ResourceManager.GetString("Str1OverwriteProjectFileAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Glossary file &quot;{0}&quot; has been modified somewhere!
        ///Do you want to update newer Mapping entries? 的當地語系化字串。
        /// </summary>
        public static string Str1UpdateGlossaryFileMappingAsk {
            get {
                return ResourceManager.GetString("Str1UpdateGlossaryFileMappingAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project file &quot;{0}&quot; has been modified somewhere!
        ///Do you want to update newer Mapping entries? 的當地語系化字串。
        /// </summary>
        public static string Str1UpdateProjectFileMappingAsk {
            get {
                return ResourceManager.GetString("Str1UpdateProjectFileMappingAsk", resourceCulture);
            }
        }
    }
}
