//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinaxWebTranslator.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinaxWebTranslator.Languages.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;p&gt;Minax Web Translator is not a translator, but just an &lt;b&gt;agent and text mapping-replacer&lt;/b&gt; for remote web translator/translation services.&lt;br&gt;
        ///It works with some online web sites and APIs, such as &lt;b&gt;Excite, CROSS-transer, Weblio, Baidu, Youdao, Google, Microsoft/Bing&lt;/b&gt; etc..&lt;/p&gt;
        ///
        ///&lt;br&gt;
        ///
        ///&lt;table border=&quot;0&quot; valign=&quot;center&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;td align=&quot;right&quot;&gt;Version: &lt;/td&gt;
        ///	&lt;td&gt;{App [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string AppAbout {
            get {
                return ResourceManager.GetString("AppAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About 的當地語系化字串。
        /// </summary>
        public static string Str0About {
            get {
                return ResourceManager.GetString("Str0About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Append 的當地語系化字串。
        /// </summary>
        public static string Str0Append {
            get {
                return ResourceManager.GetString("Str0Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Asia Pacific 的當地語系化字串。
        /// </summary>
        public static string Str0AsiaPacific {
            get {
                return ResourceManager.GetString("Str0AsiaPacific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Author 的當地語系化字串。
        /// </summary>
        public static string Str0Author {
            get {
                return ResourceManager.GetString("Str0Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Top 的當地語系化字串。
        /// </summary>
        public static string Str0AutoTop {
            get {
                return ResourceManager.GetString("Str0AutoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Str0Cancel {
            get {
                return ResourceManager.GetString("Str0Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   Chinese Converters   的當地語系化字串。
        /// </summary>
        public static string Str0ChineseConverters {
            get {
                return ResourceManager.GetString("Str0ChineseConverters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        public static string Str0Clear {
            get {
                return ResourceManager.GetString("Str0Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear and Paste 的當地語系化字串。
        /// </summary>
        public static string Str0ClearAndPaste {
            get {
                return ResourceManager.GetString("Str0ClearAndPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear and Paste from Clipboard 的當地語系化字串。
        /// </summary>
        public static string Str0ClearAndPasteFromClipboard {
            get {
                return ResourceManager.GetString("Str0ClearAndPasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string Str0Close {
            get {
                return ResourceManager.GetString("Str0Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comment 的當地語系化字串。
        /// </summary>
        public static string Str0Comment {
            get {
                return ResourceManager.GetString("Str0Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0Confirm {
            get {
                return ResourceManager.GetString("Str0Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy 的當地語系化字串。
        /// </summary>
        public static string Str0Copy {
            get {
                return ResourceManager.GetString("Str0Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Copy All 的當地語系化字串。
        /// </summary>
        public static string Str0CopyAll {
            get {
                return ResourceManager.GetString("Str0CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credits 的當地語系化字串。
        /// </summary>
        public static string Str0Credits {
            get {
                return ResourceManager.GetString("Str0Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom 的當地語系化字串。
        /// </summary>
        public static string Str0Custom {
            get {
                return ResourceManager.GetString("Str0Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Default 的當地語系化字串。
        /// </summary>
        public static string Str0Default {
            get {
                return ResourceManager.GetString("Str0Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Str0Delete {
            get {
                return ResourceManager.GetString("Str0Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0DeleteConfirm {
            get {
                return ResourceManager.GetString("Str0DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        public static string Str0Description {
            get {
                return ResourceManager.GetString("Str0Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disabled 的當地語系化字串。
        /// </summary>
        public static string Str0Disabled {
            get {
                return ResourceManager.GetString("Str0Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Duplicate Text 的當地語系化字串。
        /// </summary>
        public static string Str0DuplicateText {
            get {
                return ResourceManager.GetString("Str0DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enabled 的當地語系化字串。
        /// </summary>
        public static string Str0Enabled {
            get {
                return ResourceManager.GetString("Str0Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Europe 的當地語系化字串。
        /// </summary>
        public static string Str0Europe {
            get {
                return ResourceManager.GetString("Str0Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This field cannot be empty or full of whitespace text! 的當地語系化字串。
        /// </summary>
        public static string Str0FieldCantEmptyOrWhitespaces {
            get {
                return ResourceManager.GetString("Str0FieldCantEmptyOrWhitespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Field Error 的當地語系化字串。
        /// </summary>
        public static string Str0FieldError {
            get {
                return ResourceManager.GetString("Str0FieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Name 的當地語系化字串。
        /// </summary>
        public static string Str0FileName {
            get {
                return ResourceManager.GetString("Str0FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Full Path 的當地語系化字串。
        /// </summary>
        public static string Str0FullPath {
            get {
                return ResourceManager.GetString("Str0FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Global 的當地語系化字串。
        /// </summary>
        public static string Str0Global {
            get {
                return ResourceManager.GetString("Str0Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hyperlink 的當地語系化字串。
        /// </summary>
        public static string Str0Hyperlink {
            get {
                return ResourceManager.GetString("Str0Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   Icons   的當地語系化字串。
        /// </summary>
        public static string Str0Icons {
            get {
                return ResourceManager.GetString("Str0Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image 的當地語系化字串。
        /// </summary>
        public static string Str0Image {
            get {
                return ResourceManager.GetString("Str0Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License 的當地語系化字串。
        /// </summary>
        public static string Str0License {
            get {
                return ResourceManager.GetString("Str0License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MIT License 的當地語系化字串。
        /// </summary>
        public static string Str0MitLicense {
            get {
                return ResourceManager.GetString("Str0MitLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 New 的當地語系化字串。
        /// </summary>
        public static string Str0New {
            get {
                return ResourceManager.GetString("Str0New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        public static string Str0No {
            get {
                return ResourceManager.GetString("Str0No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NO CATEGORY 的當地語系化字串。
        /// </summary>
        public static string Str0NoCategory {
            get {
                return ResourceManager.GetString("Str0NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NO DATA 的當地語系化字串。
        /// </summary>
        public static string Str0NoData {
            get {
                return ResourceManager.GetString("Str0NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 North America 的當地語系化字串。
        /// </summary>
        public static string Str0NorthAmerica {
            get {
                return ResourceManager.GetString("Str0NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Note 的當地語系化字串。
        /// </summary>
        public static string Str0Note {
            get {
                return ResourceManager.GetString("Str0Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ok 的當地語系化字串。
        /// </summary>
        public static string Str0Ok {
            get {
                return ResourceManager.GetString("Str0Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Online Tools 的當地語系化字串。
        /// </summary>
        public static string Str0OnlineTools {
            get {
                return ResourceManager.GetString("Str0OnlineTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open 的當地語系化字串。
        /// </summary>
        public static string Str0Open {
            get {
                return ResourceManager.GetString("Str0Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Cancelled 的當地語系化字串。
        /// </summary>
        public static string Str0OperationCancelled {
            get {
                return ResourceManager.GetString("Str0OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Failed 的當地語系化字串。
        /// </summary>
        public static string Str0OperationFailed {
            get {
                return ResourceManager.GetString("Str0OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Finished 的當地語系化字串。
        /// </summary>
        public static string Str0OperationFinished {
            get {
                return ResourceManager.GetString("Str0OperationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Processing 的當地語系化字串。
        /// </summary>
        public static string Str0OperationProcessing {
            get {
                return ResourceManager.GetString("Str0OperationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Successful 的當地語系化字串。
        /// </summary>
        public static string Str0OperationSuccessful {
            get {
                return ResourceManager.GetString("Str0OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Operation Warning 的當地語系化字串。
        /// </summary>
        public static string Str0OperationWarning {
            get {
                return ResourceManager.GetString("Str0OperationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Options 的當地語系化字串。
        /// </summary>
        public static string Str0Options {
            get {
                return ResourceManager.GetString("Str0Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NOTE: other icons were re-drawn by Minax project, or come from MahApps.Metro.IconPacks library under MIT license. 的當地語系化字串。
        /// </summary>
        public static string Str0OtherIconsLicense {
            get {
                return ResourceManager.GetString("Str0OtherIconsLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Others about Minax Web Translator 的當地語系化字串。
        /// </summary>
        public static string Str0OthersAbout {
            get {
                return ResourceManager.GetString("Str0OthersAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Overwrite Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0OverwriteConfirm {
            get {
                return ResourceManager.GetString("Str0OverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paste 的當地語系化字串。
        /// </summary>
        public static string Str0Paste {
            get {
                return ResourceManager.GetString("Str0Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Select Again 的當地語系化字串。
        /// </summary>
        public static string Str0PlzSelectAgain {
            get {
                return ResourceManager.GetString("Str0PlzSelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project 的當地語系化字串。
        /// </summary>
        public static string Str0Project {
            get {
                return ResourceManager.GetString("Str0Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Project Name 的當地語系化字串。
        /// </summary>
        public static string Str0ProjectName {
            get {
                return ResourceManager.GetString("Str0ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Public Domain 的當地語系化字串。
        /// </summary>
        public static string Str0PublicDomain {
            get {
                return ResourceManager.GetString("Str0PublicDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Str0Save {
            get {
                return ResourceManager.GetString("Str0Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save As Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0SaveAsConfirm {
            get {
                return ResourceManager.GetString("Str0SaveAsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save Confirm 的當地語系化字串。
        /// </summary>
        public static string Str0SaveConfirm {
            get {
                return ResourceManager.GetString("Str0SaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        public static string Str0Settings {
            get {
                return ResourceManager.GetString("Str0Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   Softwares, Forums, and Project Hosting   的當地語系化字串。
        /// </summary>
        public static string Str0SoftForumsHosting {
            get {
                return ResourceManager.GetString("Str0SoftForumsHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Source 的當地語系化字串。
        /// </summary>
        public static string Str0Source {
            get {
                return ResourceManager.GetString("Str0Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Summary 的當地語系化字串。
        /// </summary>
        public static string Str0Summary {
            get {
                return ResourceManager.GetString("Str0Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target 的當地語系化字串。
        /// </summary>
        public static string Str0Target {
            get {
                return ResourceManager.GetString("Str0Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Temp. save secure value in this session 的當地語系化字串。
        /// </summary>
        public static string Str0TempSaveSecureValueSession {
            get {
                return ResourceManager.GetString("Str0TempSaveSecureValueSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   Third-party Toolkits, Libraries, and Controls   的當地語系化字串。
        /// </summary>
        public static string Str0ThirdPartyLibrariesControls {
            get {
                return ResourceManager.GetString("Str0ThirdPartyLibrariesControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Title 的當地語系化字串。
        /// </summary>
        public static string Str0Title {
            get {
                return ResourceManager.GetString("Str0Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translate 的當地語系化字串。
        /// </summary>
        public static string Str0Translate {
            get {
                return ResourceManager.GetString("Str0Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translator 的當地語系化字串。
        /// </summary>
        public static string Str0Translator {
            get {
                return ResourceManager.GetString("Str0Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似   Web Translators   的當地語系化字串。
        /// </summary>
        public static string Str0WebXlators {
            get {
                return ResourceManager.GetString("Str0WebXlators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        public static string Str0Yes {
            get {
                return ResourceManager.GetString("Str0Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Got Exception: {0} 的當地語系化字串。
        /// </summary>
        public static string Str1GotException {
            get {
                return ResourceManager.GetString("Str1GotException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ErrorCode: {0}, ErrorMessage: {1} 的當地語系化字串。
        /// </summary>
        public static string Str2ErrorCodeMessage {
            get {
                return ResourceManager.GetString("Str2ErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fetched {0}/{1} files. 的當地語系化字串。
        /// </summary>
        public static string Str2FetchedFilesFractions {
            get {
                return ResourceManager.GetString("Str2FetchedFilesFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The selected file &quot;{0}&quot; is stored in remote net disk drive or in a non-suitable location for following procdure.
        ///It is prefer to save it to public Document folder {1}. 的當地語系化字串。
        /// </summary>
        public static string Str2SelectedFileSaveToPublicFolderAsk {
            get {
                return ResourceManager.GetString("Str2SelectedFileSaveToPublicFolderAsk", resourceCulture);
            }
        }
    }
}
