//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinaxWebTranslator.Languages {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebXlator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebXlator() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinaxWebTranslator.Languages.WebXlator", typeof(WebXlator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 API Key 的當地語系化字串。
        /// </summary>
        public static string Str0ApiKey {
            get {
                return ResourceManager.GetString("Str0ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API Key:  的當地語系化字串。
        /// </summary>
        public static string Str0ApiKeyField {
            get {
                return ResourceManager.GetString("Str0ApiKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API Key string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0ApiKeyToolTip {
            get {
                return ResourceManager.GetString("Str0ApiKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP ID 的當地語系化字串。
        /// </summary>
        public static string Str0AppId {
            get {
                return ResourceManager.GetString("Str0AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP ID:  的當地語系化字串。
        /// </summary>
        public static string Str0AppIdField {
            get {
                return ResourceManager.GetString("Str0AppIdField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP ID string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0AppIdToolTip {
            get {
                return ResourceManager.GetString("Str0AppIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Key(APP ID) 的當地語系化字串。
        /// </summary>
        public static string Str0AppKey {
            get {
                return ResourceManager.GetString("Str0AppKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Key(APP ID):  的當地語系化字串。
        /// </summary>
        public static string Str0AppKeyField {
            get {
                return ResourceManager.GetString("Str0AppKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Key (App ID) string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0AppKeyToolTip {
            get {
                return ResourceManager.GetString("Str0AppKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Secret 的當地語系化字串。
        /// </summary>
        public static string Str0AppSecret {
            get {
                return ResourceManager.GetString("Str0AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Secret:  的當地語系化字串。
        /// </summary>
        public static string Str0AppSecretField {
            get {
                return ResourceManager.GetString("Str0AppSecretField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 APP Secret string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0AppSecretToolTip {
            get {
                return ResourceManager.GetString("Str0AppSecretToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baidu 的當地語系化字串。
        /// </summary>
        public static string Str0Baidu {
            get {
                return ResourceManager.GetString("Str0Baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baidu Translation charged APIs from China 的當地語系化字串。
        /// </summary>
        public static string Str0BaiduXlationChargedChina {
            get {
                return ResourceManager.GetString("Str0BaiduXlationChargedChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baidu Translation from China 的當地語系化字串。
        /// </summary>
        public static string Str0BaiduXlationChina {
            get {
                return ResourceManager.GetString("Str0BaiduXlationChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Baidu Translator from China 的當地語系化字串。
        /// </summary>
        public static string Str0BaiduXlatorChina {
            get {
                return ResourceManager.GetString("Str0BaiduXlatorChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Converted to .png by Minax project. 的當地語系化字串。
        /// </summary>
        public static string Str0Converted2PngByMinaxProject {
            get {
                return ResourceManager.GetString("Str0Converted2PngByMinaxProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current Translator:  的當地語系化字串。
        /// </summary>
        public static string Str0CurrentXlatorField {
            get {
                return ResourceManager.GetString("Str0CurrentXlatorField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  ErrorMessage: 的當地語系化字串。
        /// </summary>
        public static string Str0ErrorMessage {
            get {
                return ResourceManager.GetString("Str0ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Excite Translator from Japan 的當地語系化字串。
        /// </summary>
        public static string Str0ExciteXlatorJapan {
            get {
                return ResourceManager.GetString("Str0ExciteXlatorJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to clear old text, retried too manay times! 的當地語系化字串。
        /// </summary>
        public static string Str0FailedClearOldTextRetry {
            get {
                return ResourceManager.GetString("Str0FailedClearOldTextRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed localtion: {0} 的當地語系化字串。
        /// </summary>
        public static string Str0FailedLocation {
            get {
                return ResourceManager.GetString("Str0FailedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to translated strings, retried too manay times! 的當地語系化字串。
        /// </summary>
        public static string Str0FailedTranslatedRetry {
            get {
                return ResourceManager.GetString("Str0FailedTranslatedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill Google Translation API V2 (Charged) Settings 的當地語系化字串。
        /// </summary>
        public static string Str0FillGoogleApiChargedV2Settings {
            get {
                return ResourceManager.GetString("Str0FillGoogleApiChargedV2Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill Microsoft Translation API V3 (Charged) Settings 的當地語系化字串。
        /// </summary>
        public static string Str0FillMicrosoftApiChargedV3Settings {
            get {
                return ResourceManager.GetString("Str0FillMicrosoftApiChargedV3Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Google Translation from America 的當地語系化字串。
        /// </summary>
        public static string Str0GoogleXlationAmerica {
            get {
                return ResourceManager.GetString("Str0GoogleXlationAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Google Translation charged APIs from America 的當地語系化字串。
        /// </summary>
        public static string Str0GoogleXlationChargedAmerica {
            get {
                return ResourceManager.GetString("Str0GoogleXlationChargedAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Google Translator from America 的當地語系化字串。
        /// </summary>
        public static string Str0GoogleXlatorAmerica {
            get {
                return ResourceManager.GetString("Str0GoogleXlatorAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How to create API key 的當地語系化字串。
        /// </summary>
        public static string Str0HowCreateApikey {
            get {
                return ResourceManager.GetString("Str0HowCreateApikey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 How to sign-up 的當地語系化字串。
        /// </summary>
        public static string Str0HowSignUp {
            get {
                return ResourceManager.GetString("Str0HowSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 iCIBA 的當地語系化字串。
        /// </summary>
        public static string Str0Iciba {
            get {
                return ResourceManager.GetString("Str0Iciba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 iCIBA Translation from China 的當地語系化字串。
        /// </summary>
        public static string Str0IcibaXlationChina {
            get {
                return ResourceManager.GetString("Str0IcibaXlationChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input:  的當地語系化字串。
        /// </summary>
        public static string Str0InputField {
            get {
                return ResourceManager.GetString("Str0InputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input or paste source text to be translated... 的當地語系化字串。
        /// </summary>
        public static string Str0InputOrPasteSourceTextToXlated {
            get {
                return ResourceManager.GetString("Str0InputOrPasteSourceTextToXlated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Integrated Output: 的當地語系化字串。
        /// </summary>
        public static string Str0IntegratedOutput {
            get {
                return ResourceManager.GetString("Str0IntegratedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chinese Traditional 的當地語系化字串。
        /// </summary>
        public static string Str0LangChineseTraditional {
            get {
                return ResourceManager.GetString("Str0LangChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English 的當地語系化字串。
        /// </summary>
        public static string Str0LangEnglish {
            get {
                return ResourceManager.GetString("Str0LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Japanese 的當地語系化字串。
        /// </summary>
        public static string Str0LangJapanese {
            get {
                return ResourceManager.GetString("Str0LangJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LingoCloud 的當地語系化字串。
        /// </summary>
        public static string Str0LingoCloud {
            get {
                return ResourceManager.GetString("Str0LingoCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LingoCloud Translation from China 的當地語系化字串。
        /// </summary>
        public static string Str0LingoCloudXlationChina {
            get {
                return ResourceManager.GetString("Str0LingoCloudXlationChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft Translation from America 的當地語系化字串。
        /// </summary>
        public static string Str0MicrosoftXlationAmerica {
            get {
                return ResourceManager.GetString("Str0MicrosoftXlationAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft Translation charged APIs from America 的當地語系化字串。
        /// </summary>
        public static string Str0MicrosoftXlationChargedAmerica {
            get {
                return ResourceManager.GetString("Str0MicrosoftXlationChargedAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft/Bing Transltor from America 的當地語系化字串。
        /// </summary>
        public static string Str0MicrosoftXlatorAmerica {
            get {
                return ResourceManager.GetString("Str0MicrosoftXlatorAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiraiTranslate 的當地語系化字串。
        /// </summary>
        public static string Str0Mirai {
            get {
                return ResourceManager.GetString("Str0Mirai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MiraiTranslate from Japan 的當地語系化字串。
        /// </summary>
        public static string Str0MiraiXlationJapan {
            get {
                return ResourceManager.GetString("Str0MiraiXlationJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Available Regions 的當地語系化字串。
        /// </summary>
        public static string Str0MsAvailableRegions {
            get {
                return ResourceManager.GetString("Str0MsAvailableRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to navigate web translator location, retried too manay times! 的當地語系化字串。
        /// </summary>
        public static string Str0NavigateFailed {
            get {
                return ResourceManager.GetString("Str0NavigateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NOTE: Above field(s) content would be saved to private App location. If you think that is not safe, you shall not key in anything!! 的當地語系化字串。
        /// </summary>
        public static string Str0NoteSecureStore {
            get {
                return ResourceManager.GetString("Str0NoteSecureStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NOTICE: Some translator engines DO NOT support some Source Language and Target Language pair! 的當地語系化字串。
        /// </summary>
        public static string Str0NoticeSrcTgtPairMayNotSupport {
            get {
                return ResourceManager.GetString("Str0NoticeSrcTgtPairMayNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Naver Papago 的當地語系化字串。
        /// </summary>
        public static string Str0Papago {
            get {
                return ResourceManager.GetString("Str0Papago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Naver Papago Translation from Korea 的當地語系化字串。
        /// </summary>
        public static string Str0PapagoXlationKorea {
            get {
                return ResourceManager.GetString("Str0PapagoXlationKorea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input some useful text to Source box! 的當地語系化字串。
        /// </summary>
        public static string Str0PlzInputSourceBox {
            get {
                return ResourceManager.GetString("Str0PlzInputSourceBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select at least one translator! 的當地語系化字串。
        /// </summary>
        public static string Str0PlzSelectXlator {
            get {
                return ResourceManager.GetString("Str0PlzSelectXlator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preparing Translation... 的當地語系化字串。
        /// </summary>
        public static string Str0PreparingTranslation {
            get {
                return ResourceManager.GetString("Str0PreparingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quick Translation 的當地語系化字串。
        /// </summary>
        public static string Str0QuickXlation {
            get {
                return ResourceManager.GetString("Str0QuickXlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please fill some text in Quick Translation Input text box! 的當地語系化字串。
        /// </summary>
        public static string Str0QuickXlationPlzInputText {
            get {
                return ResourceManager.GetString("Str0QuickXlationPlzInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Secret Key 的當地語系化字串。
        /// </summary>
        public static string Str0SecretKey {
            get {
                return ResourceManager.GetString("Str0SecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Secret Key:  的當地語系化字串。
        /// </summary>
        public static string Str0SecretKeyField {
            get {
                return ResourceManager.GetString("Str0SecretKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Secret Key string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0SecretKeyToolTip {
            get {
                return ResourceManager.GetString("Str0SecretKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server Region:  的當地語系化字串。
        /// </summary>
        public static string Str0ServerRegionField {
            get {
                return ResourceManager.GetString("Str0ServerRegionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shrinked by Minax project. 的當地語系化字串。
        /// </summary>
        public static string Str0ShrinkedByMinaxProject {
            get {
                return ResourceManager.GetString("Str0ShrinkedByMinaxProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subscription Key for your subscription to Translator Text API 的當地語系化字串。
        /// </summary>
        public static string Str0SubKeyToolTip {
            get {
                return ResourceManager.GetString("Str0SubKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The region of the multi-service subscription 的當地語系化字串。
        /// </summary>
        public static string Str0SubMultiServiceRegion {
            get {
                return ResourceManager.GetString("Str0SubMultiServiceRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subscription Key 的當地語系化字串。
        /// </summary>
        public static string Str0SubscriptionKey {
            get {
                return ResourceManager.GetString("Str0SubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subscription Key: 的當地語系化字串。
        /// </summary>
        public static string Str0SubscriptionKeyField {
            get {
                return ResourceManager.GetString("Str0SubscriptionKeyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Weblio Translator from Japan 的當地語系化字串。
        /// </summary>
        public static string Str0WeblioXlatorJapan {
            get {
                return ResourceManager.GetString("Str0WeblioXlatorJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Where to request APP ID and Secret Key 的當地語系化字串。
        /// </summary>
        public static string Str0WhereRequestAppIdAndSecretKey {
            get {
                return ResourceManager.GetString("Str0WhereRequestAppIdAndSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Where to request App Key (App ID) and App Secret 的當地語系化字串。
        /// </summary>
        public static string Str0WhereRequestAppKeyAndAppSecret {
            get {
                return ResourceManager.GetString("Str0WhereRequestAppKeyAndAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating Cancelled 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingCancelled {
            get {
                return ResourceManager.GetString("Str0XlatingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating Failed 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingFailed {
            get {
                return ResourceManager.GetString("Str0XlatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translation failed!
        ///Maybe some necessary field(s) is/are missing or mis-typed when using Translation API (Charged)? 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingFailedFieldMissing {
            get {
                return ResourceManager.GetString("Str0XlatingFailedFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating failed!
        ///Please retry latter! Maybe the network is disconnected, or remote web site is busy. 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingFailedNetRetry {
            get {
                return ResourceManager.GetString("Str0XlatingFailedNetRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating Result 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingResult {
            get {
                return ResourceManager.GetString("Str0XlatingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating succeed! 的當地語系化字串。
        /// </summary>
        public static string Str0XlatingSucceed {
            get {
                return ResourceManager.GetString("Str0XlatingSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translation API 的當地語系化字串。
        /// </summary>
        public static string Str0XlationApi {
            get {
                return ResourceManager.GetString("Str0XlationApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translator Selector 的當地語系化字串。
        /// </summary>
        public static string Str0XlatorSelector {
            get {
                return ResourceManager.GetString("Str0XlatorSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CROSS-Transer Translation from Japan 的當地語系化字串。
        /// </summary>
        public static string Str0XTranserXlationJapan {
            get {
                return ResourceManager.GetString("Str0XTranserXlationJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CROSS-Transer Translator from Japan 的當地語系化字串。
        /// </summary>
        public static string Str0XTranserXlatorJapan {
            get {
                return ResourceManager.GetString("Str0XTranserXlatorJapan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youdao 的當地語系化字串。
        /// </summary>
        public static string Str0Youdao {
            get {
                return ResourceManager.GetString("Str0Youdao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youdao Translation charged APIs from China 的當地語系化字串。
        /// </summary>
        public static string Str0YoudaoXlationChargedChina {
            get {
                return ResourceManager.GetString("Str0YoudaoXlationChargedChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youdao Translation from China 的當地語系化字串。
        /// </summary>
        public static string Str0YoudaoXlationChina {
            get {
                return ResourceManager.GetString("Str0YoudaoXlationChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youdao Translator from China 的當地語系化字串。
        /// </summary>
        public static string Str0YoudaoXlatorChina {
            get {
                return ResourceManager.GetString("Str0YoudaoXlatorChina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} string for your subscription to Translation API 的當地語系化字串。
        /// </summary>
        public static string Str1FieldForApiToolTip {
            get {
                return ResourceManager.GetString("Str1FieldForApiToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fill {0} Translation API (Charged) Settings 的當地語系化字串。
        /// </summary>
        public static string Str1FillXlationApiChargedSettings {
            get {
                return ResourceManager.GetString("Str1FillXlationApiChargedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Quick Translation Input text count is exceed {0}! 的當地語系化字串。
        /// </summary>
        public static string Str1QuiclXlationInputCountMax {
            get {
                return ResourceManager.GetString("Str1QuiclXlationInputCountMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Something wrong when translating, StatusCode: {0} 的當地語系化字串。
        /// </summary>
        public static string Str1TranslateError {
            get {
                return ResourceManager.GetString("Str1TranslateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tanslating error:  {0} 的當地語系化字串。
        /// </summary>
        public static string Str1TranslatingError {
            get {
                return ResourceManager.GetString("Str1TranslatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating aborted! Exception: {0} 的當地語系化字串。
        /// </summary>
        public static string Str1XlatingAbortedException {
            get {
                return ResourceManager.GetString("Str1XlatingAbortedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating failed! Exception: {0} 的當地語系化字串。
        /// </summary>
        public static string Str1XlatingFailedException {
            get {
                return ResourceManager.GetString("Str1XlatingFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Translation API (Charged) 的當地語系化字串。
        /// </summary>
        public static string Str1XlationApiCharged {
            get {
                return ResourceManager.GetString("Str1XlationApiCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} API (Free) 的當地語系化字串。
        /// </summary>
        public static string Str1XlationApiFree {
            get {
                return ResourceManager.GetString("Str1XlationApiFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input some text to be translated, count: {0}/{1} 的當地語系化字串。
        /// </summary>
        public static string Str2InputTextCountFractions {
            get {
                return ResourceManager.GetString("Str2InputTextCountFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}/{1} Translated 的當地語系化字串。
        /// </summary>
        public static string Str2TranslatedFractions {
            get {
                return ResourceManager.GetString("Str2TranslatedFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Something wrong when translating, ErrorCode: {0}, Message: {1} 的當地語系化字串。
        /// </summary>
        public static string Str2TranslateErrorMessage {
            get {
                return ResourceManager.GetString("Str2TranslateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Translating failed! ErrorCode: {0}, ErrorMessage: {1} 的當地語系化字串。
        /// </summary>
        public static string Str2TranslatingErrorMessage {
            get {
                return ResourceManager.GetString("Str2TranslatingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Youdao does not support translate from {0} to {1} 的當地語系化字串。
        /// </summary>
        public static string Str2YoudaoNotSupportSrc2Tgt {
            get {
                return ResourceManager.GetString("Str2YoudaoNotSupportSrc2Tgt", resourceCulture);
            }
        }
    }
}
